exclude: ^mkspecs/.*/qplatformdefs\.h$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
#     - id: no-commit-to-branch
#       args: ['--branch', 'main']
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
      - id: remove-tabs
      - id: remove-crlf
      - id: forbid-tabs
      - id: forbid-crlf
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: ['-i']
      - id: clang-tidy
        args: ['--config-file=.clang-tidy',
               '--',
               '-x', 'c++',
               '-I/usr/include/x86_64-linux-gnu/qt5/',
               '-I/usr/include/x86_64-linux-gnu/qt5/QtCore/',
               '-I/usr/include/x86_64-linux-gnu/qt5/QtNetwork/',
               '-I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineWidgets/',
               '-I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/',
               '-ILibHimbeer/']
      - id: cppcheck
        args: ['--language=c++',
               '--enable=all']
      - id: cpplint
        args: ['--filter=-build/header_guard,
                         -build/include_order,
                         -legal/copyright,
                         -readability/nolint,
                         -whitespace/braces,
                         -whitespace/comments,
                         -whitespace/indent,
                         -whitespace/newline',
               '--linelength=100']
  - repo: https://github.com/hurzelchen/pre-commit-hooks
    rev: 91efe08
    hooks:
     - id: clazy
       args: ['-Xclang', '-plugin-arg-clazy',
              '-Xclang', 'level0,level1,level2,ifndef-define-typo,isempty-vs-count,signal-with-return-value,tr-non-literal,use-arrow-operator-instead-of-data,use-chrono-in-qtimer',
              '-x', 'c++',
              '-fPIC',
              '-include/usr/include/stdint.h',
              '-isystem/usr/include/c++/11/',
              '-isystem/usr/lib/llvm-14/lib/clang/14.0.0/include/',
              '-isystem/usr/include/x86_64-linux-gnu/qt5/',
              '-isystem/usr/include/x86_64-linux-gnu/qt5/QtCore/',
              '-isystem/usr/include/x86_64-linux-gnu/qt5/QtNetwork/',
              '-isystem/usr/include/x86_64-linux-gnu/qt5/QtWebEngineWidgets/',
              '-isystem/usr/include/x86_64-linux-gnu/qt5/QtWidgets/',
              '-ILibHimbeer/']
       entry: env CLAZY_IGNORE_DIRS=/usr/.* hurzelchen-clazy
     - id: include-what-you-use
       args: ['-Xiwyu', '--mapping_file=.iwyu-mapping.imp',
              '-Xiwyu', '--max_line_length=100',
              '-Xiwyu', '--quoted_includes_first',
              '-x', 'c++',
              '-fPIC',
              '-include/usr/include/stdint.h',
              '-I/usr/include/c++/11/',
              '-I/usr/lib/llvm-14/lib/clang/14.0.0/include/',
              '-I/usr/include/x86_64-linux-gnu/qt5/',
              '-I/usr/include/x86_64-linux-gnu/qt5/QtCore/',
              '-I/usr/include/x86_64-linux-gnu/qt5/QtNetwork/',
              '-I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineWidgets/',
              '-I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/',
              '-ILibHimbeer/']
