repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
#     - id: no-commit-to-branch
#       args: ['--branch', 'main']
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
      - id: clang-tidy
        args: ['--config-file=.clang-tidy',
               '--',
               '-x', 'c++',
               '-I/usr/include/x86_64-linux-gnu/qt5/',
               '-I/usr/include/x86_64-linux-gnu/qt5/QtCore/',
               '-I/usr/include/x86_64-linux-gnu/qt5/QtNetwork/',
               '-I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/']
      - id: cppcheck
        args: ['--language=c++']
      - id: cpplint
        args: ['--filter=-build/header_guard,
                         -legal/copyright,
                         -whitespace/braces,
                         -whitespace/comments,
                         -whitespace/indent,
                         -whitespace/newline',
               '--linelength=100']
  - repo: https://github.com/hurzelchen/pocc-pre-commit-hooks
    rev: v1.3.6
    hooks:
     - id: include-what-you-use
       args: ['-Xiwyu',
              '--mapping_file=.iwyu-mapping.imp',
              '-fPIC',
              '-x', 'c++',
              '-I/usr/include/c++/11/',
              '-I/usr/lib/llvm-14/lib/clang/14.0.0/include/',
              '-I/usr/include/x86_64-linux-gnu/qt5/',
              '-I/usr/include/x86_64-linux-gnu/qt5/QtCore/',
              '-I/usr/include/x86_64-linux-gnu/qt5/QtNetwork/',
              '-I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/']
